### ISSUE TITLE
Unable to find manifest file with an "_" in its file name

### ISSUE THREAD

**Issue by danrabbit** [elementary/action-appcenter-review-find-manifest#1]
I'm not sure if this is intentional because of a limitation in Flatpak builder or just an oversight, but we're failing to find the manifest file for https://github.com/elementary/appcenter-reviews/pull/77 and I'm guessing it's probably because the file name contains an "_" character

**Comment by btkostner** [comment]
This issue is not due to the find-manifest action. The RDNN is parsed from the file path in the repository, so we have to do two things:

- Update the file in the nasc PR to use an underscore instead of a dash
- Update the parse action regex to include underscores

See output from the parse action: https://github.com/elementary/appcenter-reviews/pull/77/checks?check_run_id=3384846343#step:3:13
